課題3-4 first commit
yoshiblog-space/task3-2 pull request #3
Opened 2020-12-16 03:27 UTC by yoshiblog-space

課題３ー４対応いたしました！
タスク表示/非表示切り替え機能
【要件】
- タスクの状態によって表示/非表示を切り替えできる
- 選択されたラジオボタンに応じて、タスクの表示を切り替える
- 「作業中」選択時にタスクを新規追加した場合、タスクが表示される
- 「完了」選択時にタスクを新規追加した場合、タスクは表示されない（が、裏ではちゃんと追加されている）

2020-12-16 12:13 UTC, myzktkyk requested changes
動作は問題ありませんでした。
コードについて一点軽微な指摘をしております。

2020-12-16 12:13 UTC, myzktkyk commented on js/main.js
> +  let alltodo = document.getElementById('alltodo');
再代入はしないと思うので `const` でいいと思います。
以降の類似箇所も全て同様ですね。

```suggestion
  const alltodo = document.getElementById('alltodo');
```

2020-12-16 12:25 UTC, yoshiblog-space commented
下記内容について修正いたしました！
ご確認の程よろしくお願いいたします。

・再代入はしないletを constへ変更
　→3箇所修正

2020-12-18 00:41 UTC, kouki-iwahara reviewed
コメントしましたのでご確認ください。

2020-12-18 00:41 UTC, kouki-iwahara commented on js/main.js
>    let changeTodo = (changeRow) => {
ここもconstで定義できます。
再代入されるのか・されないのかを考えながら記述すると良いですね^^

2020-12-18 10:47 UTC, merged